### PR TITLE
Introduce `@cable_ready/polyfills` and sync javascript changes from stimulus_reflex

### PR DESCRIPTION
**Pull request by marcoroth**
# Type of PR

Feature

## Description

This PR applies all of the changes from hopsoft/stimulus_reflex#340, ~hopsoft/stimulus_reflex#315~ (reverted) and hopsoft/stimulus_reflex#345 to `cable_ready`. 

This includes:

* Introduce lerna for multiple npm packages handling
* Introduce `@cable_ready/polyfills`
* Move `javascript/` to `packages/@cable_ready/core`

## Why should this be added

Applies everything to the `cable_ready` JavaScript part that was introduced to the `stimulus_reflex` JavaScript part. Including the same structure for multiple npm packages and polyfills package for the support of CableReady in older browsers.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] Checks (StandardRB & Prettier-Standard) are passing
- [x] This is not a documentation update

### CODE REVIEW

**Comment by marcoroth** [comment]
We still need to clarify if and how we need to polyfill these:

* `Notifications`
* `XPathResult`
* `element.style`

caniuse.com says the first two are not compatible with IE11.

**Comment by marcoroth** [comment]
Okay, it looks like `Notification` and `XPathResult` are simple to polyfill - at least I found no good solution for it.
I would say we leave them out for now. So we can merge this.

**Comment by leastbad** [comment]
Is https://adodson.com/notification.js/ a possible solution for Notification?

**Comment by marcoroth** [comment]
Closing in favor of #165.

**Pull request closed without merging**
