### PR TITLE
Add setting switch to disable assets compilation

### PR DESCRIPTION
**Pull request by n-rodriguez**
Like ActionCable: https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/engine.rb#L27 

Useful when using Webpacker to manage static assets

- [ ] My code follows the style guidelines of this project
- [ ] Checks (StandardRB & Prettier-Standard) are passing
- [ ] This is not a documentation update

### CODE REVIEW

**Comment by marcoroth** [comment]
Thanks @n-rodriguez! I thought we had that already, but seems like we don't!

I'm wondering if we should do it like `turbo-rails` does it?

https://github.com/hotwired/turbo-rails/blob/6db05d69d5f060bd142defe247550b5da5c47228/lib/turbo/engine.rb#L23-L35

**Comment by n-rodriguez** [comment]
I'd prefer to not touch [CableReady::Config](https://github.com/stimulusreflex/cable_ready/blob/master/lib/cable_ready/config.rb) so let's do it à la Turbo :)

**Comment by marcoroth** [comment]
> I'd prefer to not touch `CableReady::Config`

@n-rodriguez Do you have any specific reason for that?

**Comment by n-rodriguez** [comment]
> @n-rodriguez Do you have any specific reason for that?

to keep things simple

**Comment by n-rodriguez** [comment]
Actually I don't use the `main` branch of CableReady, I use `5.0.0.pre9` for both Ruby and JS so I'm not aware of the changes in the APIs.

Maybe this is better :

```ruby
# config/initializers/cable_ready.rb
CableReady.configure do |config|
  config.precompile_assets = false # new configuration accessor

  config.on_failed_sanity_checks = :ignore

  config.add_operation_name :notify
  config.add_operation_name :progress_bar
end
```
but it may requires some tests. wdyt?

**Comment by n-rodriguez** [comment]
FWIW :

Turbo : https://github.com/hotwired/turbo-rails/blob/main/lib/turbo/engine.rb#L31
ActionText: https://github.com/rails/rails/blob/main/actiontext/lib/action_text/engine.rb#L33
ActionCable: https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/engine.rb#L27
ActiveStorage: https://github.com/rails/rails/blob/main/activestorage/lib/active_storage/engine.rb#L189

**Comment by marcoroth** [comment]
@n-rodriguez I like the version where we have it in `config/initializers/cable_ready.rb` 👍🏼 

but we can also keep the `PRECOMPILE_ASSETS` constant so you could also do it the other way if you like.

For ActionText, ActionCable and ActiveStorage it makes sense that they do it that way because the already have their regular a config on `application.config`

**Comment by marcoroth** [comment]
One more thing: Would you mind adding it commented out to: https://github.com/stimulusreflex/cable_ready/blob/29b7e063465acb0468ecd3d4034b0c00696c7f07/lib/generators/cable_ready/templates/config/initializers/cable_ready.rb#L3 

Then we can merge this, imo 🚀

**Comment by n-rodriguez** [comment]
> Then we can merge this, imo rocket

Do you think it's possible to cut a new pre-release for both Ruby and JS?

**Comment by marcoroth** [comment]
Yes, pre10 is going out this week!

**Review by marcoroth — APPROVED** [review]
Thank you @n-rodriguez!

**Comment by n-rodriguez** [comment]
> Yes, pre10 is going out this week!

Thanks!

**Pull request merged**
